### ISSUE TITLE
Add date to club opening push notifications

### ISSUE THREAD

**Issue by FrNecas** [ondryaso/kachna-online#84]
The push notification may be shown by the browser a lot later than it was initially sent (happened to me on desktop in Firefox) making it a bit confusing to the user whether the club is really open. Include date in the notification text (possibly also check if there is a way to include the date in the push protocol but I don't remember seeing it).

**Comment by ondryaso** [comment]
Added in b61680f8892df6bc39ecb892d7af661db8c64502
